// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Feed",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Feed",
            targets: ["Feed"],
            bundleIdentifier: "eu.drmax.DrMaxNavigation.Feed",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .checkmark),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "swift-drmax-navigation", path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "Feed",
            dependencies: [
                .product(name: "DrMaxNavigation", package: "swift-drmax-navigation")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)